### ISSUE TITLE
Rival 310 buttons mapping 

### ISSUE THREAD

**Issue by flozz** [FFY00/rival310-re#1]
Hello,

I am working on a new major version of [Rivalcfg][], the [v4.0][], that is an almost complete rewrite of the software and I just added support of the buttons mapping feature.

As the Sensei [RAW], the Rival, Rival 300, Rival 700 and Rival 710 seems to implement it in a very similar way, I think that the Rival 310 should also work the same.

As I do not own this device, I ask you if you can help me with this by capturing some packet to check if it works the same and to get some mouse-specific values. :)

[Rivalcfg]: https://github.com/flozz/rivalcfg/tree/master>
[v4.0]: https://github.com/flozz/rivalcfg/tree/rivalcfg4.0

**Comment by FFY00** [comment]
It should be pretty similar too, if not the same.

I am a bit busy, can you see if the libratbag driver has the information you need? Otherwise, I'll capture some packets.

https://github.com/libratbag/libratbag/blob/master/src/driver-steelseries.c

**Comment by flozz** [comment]
I will look at this, thank you :)

**Comment by flozz** [comment]
I close this issue as SteelSeries sent me a Sensei 310, I was able to check everything I needed by myself. Thank you again :)
